name: Build and push .NET packages

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GGroupp NuGet Source
      run: >
        dotnet nuget add source ${{ secrets.GGROUPP_NUGET_SOURCE_URL }}
        -n ggroupp
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    # Bot.Builder.Core.csproj

    - name: Restore Bot.Builder.Core.csproj
      run: dotnet restore ./src/*/Bot.Builder.Core.csproj

    - name: Build Bot.Builder.Core.csproj
      run: dotnet build ./src/*/Bot.Builder.Core.csproj --no-restore  -c Release

    - name: Pack Bot.Builder.Core.csproj
      run: dotnet pack ./src/*/Bot.Builder.Core.csproj --no-restore -o ~/nuget  -c Release

    # Bot.Builder.FlowFailure.csproj

    - name: Restore Bot.Builder.FlowFailure.csproj
      run: dotnet restore ./src/*/Bot.Builder.FlowFailure.csproj

    - name: Build Bot.Builder.FlowFailure.csproj
      run: dotnet build ./src/*/Bot.Builder.FlowFailure.csproj --no-restore  -c Release

    - name: Pack Bot.Builder.FlowFailure.csproj
      run: dotnet pack ./src/*/Bot.Builder.FlowFailure.csproj --no-restore -o ~/nuget  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s ${{ secrets.GG_NUGET_SOURCE_URL }}
        -k ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --skip-duplicate